### ISSUE TITLE
[Task Card] 과제 분석 - 요구사항 명세 

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/payHere-Wanted-A#1]
### **ISSUE**

- Group: `A Team`
- Type: `analysis`
- Detail: 과제 분석 - 요구사항 명세

### **TODO**

- [x] 요구사항 분석하기 (README.md)
- [x] REST API 만들기
- [x] 일정 정리하기 (칸반보드)
- [x] 팀원별 Task Card 나누기

### **Labels**

- Estimated time: `E: 3h`
- Group : `A Team`
- Urgency: `High`
