### ISSUE TITLE
[Task Card] 테스트 코드 (1) - 회원 관련

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/payHere-Wanted-A#13]
### **ISSUE**

- Group: `A Team`
- Type: `feature`
- Detail: 테스트 코드 작성하기 - 회원관련

### **TODO**

- [ ] 회원가입 테스트 코드 작성하기
- [ ] 로그인 테스트 코드 작성하기
- [ ] 로그아웃 테스트 코드 작성하기
- [ ] 회원정보 조회 테스트 코드 작성하기

### **Labels**

- Estimated time: `E: 4h`
- Group : `A Team`
- Urgency: `High`
