### ISSUE TITLE
[Task Card] 테스트 코드 (2) - 가계부 관련

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/payHere-Wanted-A#14]
### **ISSUE**

- Group: `A Team`
- Type: `feature`
- Detail: 테스트 코드 작성하기 - 가계부 관련

### **TODO**

- [ ] 가계부 등록 테스트 코드 작성하기
- [ ] 가계부 수정 테스트 코드 작성하기
- [ ] 가계부 삭제 테스트 코드 작성하기
- [ ] 삭제 가계부 리스트 테스트 코드 작성하기
- [ ] 삭제 가계부 복원 테스트 코드 작성하기
- [ ] 가계부 리스트 테스트 코드 작성하기
- [ ] 가계부 상세 내역 테스트 코드 작성하기

### **Labels**

- Estimated time: `E: 4h`
- Group : `A Team`
- Urgency: `High`
