### ISSUE TITLE
[Task Card] 초기 설정(1)

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/payHere-Wanted-A#2]
### **ISSUE**

- Group: `A Team`
- Type: `setting`
- Detail: 초기 설정하기

### **TODO**

- [x] DB 설계하기 (erd 생성)
- [x] DDL 작성하기
- [x] 파일 구조 정하기
- [x] package.json 구성하기

### **Labels**

- Estimated time: `E: 1.5h`
- Group : `A Team`
- Urgency: `High`
