### ISSUE TITLE
[Task Card] 회원가입, 로그인, 로그아웃, 회원정보 조회 기능 구현 (with JWT)

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/payHere-Wanted-A#4]
### **ISSUE**

- Group: `A Team`
- Type: `feature`
- Detail: 로그인, 로그아웃, 회원가입 기능 구현 (JWT 방식 사용)

### **TODO**

- [x] JWT(인증제어) 메서드 구현하기
- [x] 회원가입 구현하기
- [x] 로그인 구현하기
- [x] 로그아웃 구현하기
- [x] 회원정보 조회 구현하기
- [x] validate 구현하기 (입력 정보 검증 메서드)
- [x] 클라이언트 구현하기

### **Labels**

- Estimated time: `E: 4h`
- Group : `A Team`
- Urgency: `High`
